apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-k8s
  name: hello-k8s
spec:
  ports:
  - name: "8082"
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: hello-k8s
  type: ClusterIP
status:
  loadBalancer: {}
